name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.78.0 # minimum supported version
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust}}
          components: rustfmt
      - name: Build
        run: cargo build
      - name: Cargo Test
        run: cargo test --all
      - name: Format (fix with `cargo fmt`)
        run: cargo fmt -- --check
      - name: Run unit-tests
        run: tests/run_all.sh
        shell: bash

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Build
        run: cargo build
      - name: Cargo Test
        run: cargo test --all
      - name: Run unit-tests
        run: tests/run_all.sh
        shell: bash

  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy --all-features

  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [test, clippy_check]
    if: always()
    steps:
      - name: Check required jobs
        run: |
          if [[ "${{ needs.test.result }}" != "success" || "${{ needs.clippy_check.result }}" != "success" ]]; then
            echo "Required Linux tests failed"
            exit 1
          fi
          echo "All required tests passed"
